spring:
  datasource:
    url: jdbc:postgresql://localhost:1234/golfstream2.0
    username: postgres
    password: 23122002Nik
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update

