spring:
  datasource:
    url: jdbc:postgresql://localhost:1234/golfstream2.0
    username: postgres
    password: 23122002Nik
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
security:
  jwt:
    access: 300000
    refresh: 2592000000
    secret: o24UJSO93eJ=kXd;R40V6?E1fYc59-lavSlu

